CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    annotation        VARCHAR(2000) NOT NULL,

    category_id       BIGINT NOT NULL,
    initiator_id      BIGINT NOT NULL,

    created           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description       VARCHAR(7000) NOT NULL,
    event_date        TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    location_id       BIGINT NOT NULL,

    paid              BOOLEAN NOT NULL DEFAULT false,
    participant_limit INTEGER,
    published         TIMESTAMP WITHOUT TIME ZONE,
    moderate          BOOLEAN NOT NULL DEFAULT true,
    state             VARCHAR(20) NOT NULL,
    title             VARCHAR(120) NOT NULL,

    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT fk_events_location
        FOREIGN KEY (location_id) REFERENCES locations (id)
);

